import SGA
import time
print("附录一 蒸汽发生器热力计算")
print("一、热平衡")
print("1.一回路放热量\t Q\t\t",SGA.Q)
print("2.一回路工作压力\t p1\t\t",SGA.matr.P_loop_1)
print("3.一回路水进口温度\t t1'\t",SGA.matr.T_loop_1_i)
print("4.一回路水出口温度\t t1''\t",SGA.matr.T_loop_1_o)
print("5.一回路水平均温度\t ta\t\t",SGA.AT_loop_1)
print("6.一回路水进口焓\t i1' \t",SGA.i1_i)
print("7.一回路水出口焓\t i1'' \t",SGA.i1_o)
print("8.蒸发器热效率\t η\t\t",SGA.matr.SG_yita)
print("9.一回路水流量\t G1 \t",SGA.G_loop1)
print("10.二回路工作压力\t ps \t",SGA.matr.P_loop_2_s)
print("11.二回路饱和温度\t ts \t",SGA.matr.T_2_s)
print("12.二回路水饱和焓\t is \t",SGA.i_s)
print("13.二回路给水温度\t tf \t",SGA.matr.T_2_in)
print("14.二回路给水焓\t if   \t",SGA.i_f)
print("15.汽化潜热    \t r   \t",SGA.r)
print("16.蒸汽干度    \t x   \t",SGA.matr.x)
print("17.排放系数    \t Cs  \t","未给定")
print("18.二回路蒸汽产量\t D  \t",SGA.matr.D)
print("19.二回路排污量\t Dd   \t",SGA.matr.D_d)

print("二、传热计算")
print("20.传热管外径       \t do     \t",SGA.matr.d_o)
print("21.传热管内径       \t di     \t",SGA.matr.d_i)
print("22.单管流通面积     \t a      \t",SGA.pip.a)
print("23.U型管数目        \t n      \t",0.5*SGA.N)
print("24.一回路流通面积    \t A      \t",SGA.A)
print("25.一回路水平均比容  \t nu1     \t",SGA.v_f)
print("26.一回路水流速     \t u1      \t",SGA.u_f)
print("27.一回路水导热系数  \t lambda1 \t",SGA.lamb_f)
print("28.一回路水动力粘度  \t eta1    \t",SGA.mu_f)
print("29.一回路水普朗特数  \t Prf     \t",SGA.Pr_f)
print("30.一回路水雷诺数    \t Ref     \t",SGA.Re_f)
print("31.一回路侧放热系数  \t alpha1   \t",SGA.h_i)
print("32.传热管导热系数    \t lambdaw  \t",SGA.matr.lamb_w)
print("33.传热管壁热阻      \t Rw       \t",SGA.R_w)
print("34.污垢热阻         \t Rf       \t",SGA.R_f)
print("35.二回路侧放热系数  \t alpha2   \t",SGA.h_o)
print("36.传热系数         \t k        \t",SGA.k)
print("37.大端温差         \t A        \t",SGA.matr.T_loop_1_i-SGA.matr.T_2_s)
print("38.小端温差         \t A        \t",SGA.matr.T_loop_1_o-SGA.matr.T_2_s)
print("39.对数平均温差      \t Dtln     \t",SGA.DTln)
print("40.热负荷           \t q        \t",SGA.q)
print("41.计算传热面积      \t F        \t",SGA.F)
print("42.传热裕度系数      \t         \t",SGA.matr.C)
print("43.设计传热面积      \t F设      \t",SGA.F_w)

print("三、管束结构")
print("1.传热管总长         \t L总   \t",SGA.L_tot)
print("2.排列方式          \t     \t","正方形")
print("3.节距              \t t   \t",SGA.matr.t)
print("4.最小U型管节圆直径   \t D节   \t",4*SGA.matr.t)
print("5.实际布管数         \t n   \t",0.5*SGA.N)
print("6.管束直径          \t Dtb   \t",SGA.D_tb)
print("7.弯管总长          \t L弯   \t",SGA.R_part)
print("8.直管总长          \t L直   \t",SGA.L_str)
print("9.管束直段高        \t H直   \t",SGA.matr.L)
print("10.管束弯段高       \t H弯   \t",SGA.R_max)
print("11.管束总高         \t Htb   \t",SGA.H_pips)
print("12.传热管实际平均长度 \t l    \t",SGA.l_aver)
print("13.最长管子长        \t Lmax \t",SGA.L_max)
print("14.最短管子长        \t lmin \t",SGA.L_min)

print("四、主要管道内径")
print("1.冷却剂平均比容      \t nu     \t",SGA.v_f)
print("2.主管道计算流速      \t u'10   \t",SGA.matr.u_1_0_c)
print("3.主管道计算内径      \t d'1i   \t",SGA.d_1_i_c)
print("4.主管道设计内径      \t d1i    \t",SGA.d_1_i)
print("5.主管道设计流速      \t u10    \t",SGA.u_1_0)
print("6.新蒸汽比容          \t v2     \t",SGA.v_2)
print("7.蒸汽管计算流速      \t u'2    \t",SGA.matr.u_2_c)
print("8.蒸汽管计算内径      \t d'2i   \t",SGA.d_2_i_c)
print("9.蒸汽管设计内径      \t d2i    \t",SGA.d_2_i)
print("10.蒸汽管设计流速     \t u2     \t",SGA.u_2)
print("11.二回路给水比容     \t v3     \t",SGA.v_3)
print("12.给水管计算流速     \t u'3    \t",SGA.matr.u_3_c)
print("13.给水管计算内径     \t d'3i   \t",SGA.d_3_i_c)
print("14.给水管设计内径     \t d3i    \t",SGA.d_3_i)
print("15.给水管设计流速     \t u3     \t",SGA.u_3)

print("附录二 蒸汽发生器水力计算")
print("I 一回路水阻力计算")
print("一、 U型管内摩擦阻力计算")
print("1.传热管实际平均长度      \t l      \t",SGA.l_aver)
print("2.当量直径              \t di     \t",SGA.matr.d_i)
print("3.一回路水流量           \t G1     \t",SGA.G_loop1)
print("4.一回路水平均比容        \t v1     \t",SGA.v_f)
print("5.一回路水流速           \t u1     \t",SGA.u_f)
print("6.考虑堵管后流速         \t u'1     \t",SGA.u_f_pip)
print("7.一回路水雷诺数         \t Re      \t",SGA.Re_f)
print("8.摩擦阻力系数           \t lambda  \t",SGA.lamb)
print("9.平均温度下动力粘度      \t eta1    \t",SGA.mu_f)
print("10.壁温下动力粘度        \t eta'1   \t",SGA.mu_f_wall)
print("11.温度修正系数          \t phi     \t",SGA.phi)
print("12.摩擦阻力             \t ΔPf     \t",SGA.P_f)

print("二、 局部阻力计算")
print("13.下封头内径         \t D1     \t",SGA.D_down)
print("14.水室截面积         \t Fc     \t",SGA.F_c)
print("15.进口管内径         \t d1i    \t",SGA.d_1_i)
print("16.进口管截面积       \t A1     \t",SGA.A_1_i)
print("17.比值              \t        \t",SGA.ApF)
print("18.突扩阻力系数       \t eps1   \t",SGA.epsilon1)
print("19.一回路入水口处比容  \t v1i    \t",SGA.v_1_i)
print("20.一回路入水口处密度  \t rho1i  \t",SGA.rho_1_i)
print("21.入口管内流速       \t u1i    \t",SGA.u_1_0)
print("22.从入口管到水室阻力  \t ΔP1    \t",SGA.P_1)
print("23.水室转弯45度阻力系数\t eps2   \t",SGA.epsilon2)
print("24.水室转弯45度阻力    \t ΔP2    \t",SGA.P_2)
print("25.传热管流道截面     \t A       \t",SGA.A)
print("26.考虑有堵管后截面    \t A'     \t",SGA.A_pips)
print("27.系数              \t        \t",SGA.ApippF)
print("28.传热管入口阻力系数  \t eps3   \t",SGA.epsilon3)
print("29.传热管入口阻力      \t ΔP3    \t",SGA.P_3)
print("30.U型管转180度阻力系数\t eps4   \t",SGA.epsilon4)
print("31.U型管转180度阻力    \t ΔP4    \t",SGA.P_4)
print("32.传热管出口阻力系数   \t eps5   \t",SGA.epsilon5)
print("33.出口处水比容        \t v2     \t",SGA.v_1_o)
print("34.出口处水密度        \t rho2   \t",SGA.rho_1_o)
print("35.传热管出口阻力      \t ΔP5    \t",SGA.P_5)
print("36.出口管内流速       \t u2      \t",SGA.u_1_o)
print("37.水室转弯阻力系数    \t eps6    \t",SGA.epsilon6)
print("38.水室转弯阻力       \t ΔP6      \t",SGA.P_6)
print("39.出口管突缩阻力系数  \t eps7     \t",SGA.epsilon7)
print("40.出口管突缩阻力     \t ΔP7      \t",SGA.P_7)

print("三、 总阻力")
print("41.总阻力      \t ΔP      \t",SGA.P_tot_c)
print("42.设计阻力    \t ΔP设     \t",SGA.P_tot)

print("II 二回路水循环阻力计算")
print("一、 下降阻力计算")
print("1.循环倍率           \t CR     \t",SGA.CR)
print("2.给水温度           \t tf     \t",SGA.matr.T_2_in)
print("3.二回路饱和温度      \t ts     \t",SGA.matr.T_2_s)
print("4.下降空间水比容      \t vd     \t",SGA.v_f_2)
print("5.下降空间水密度      \t rhod   \t",SGA.rho_f_2)
print("6.入口阻力系数        \t epsin  \t",SGA.matr.epsilon_in)
print("7.出口阻力系数        \t epsout \t",SGA.matr.epsilon_out)
print("8.定位装置阻力系数     \t epsf    \t",SGA.matr.epsilon_poi)
print("9.下降空间高度        \t H0     \t",SGA.H_down)
print("10.套筒外径          \t Dw0    \t",SGA.D_w_o)
print("11.下筒体内径         \t Dsi    \t",SGA.D_s_i)
print("12.下降空间当量直径    \t De     \t",SGA.De)
print("13.绝对粗燥度         \t Δ      \t",SGA.matr.delta_down)
print("14.摩擦系数          \t lambd  \t",SGA.lamb_d)
print("15.下降空间截面积     \t Fd     \t",SGA.F_d)
print("16.下降空间水流速     \t ud     \t",SGA.u_d)
print("17.下降空间阻力       \t ΔPd    \t",SGA.P_d)

print("二、 上升空间阻力计算")
print("1、 摩擦阻力")
print("1.饱和水比容                    \t v'        \t",SGA.v_f_2)
print("2.饱和水密度                    \t rho'      \t",SGA.rho_f_2)
print("3.饱和蒸汽比容                  \t v''       \t",SGA.v_f_s_2)
print("4.饱和蒸汽密度                  \t rho''     \t",SGA.rho_f_s_2)
print("5.套筒内径                      \t Dw1       \t",SGA.D_w_i)
print("6.传热管外径                    \t do        \t",SGA.matr.d_o)
print("7.支撑板定位拉杆数量              \t n'       \t",SGA.n_l)
print("8.上升空间流通面积               \t Fu        \t",SGA.F_u)
print("9.上升空间当量直径               \t de        \t",SGA.de)
print("10.循环速度                     \t uo        \t",SGA.u_o)
print("11.出口水相折算速度              \t u'o2      \t",SGA.u_o_l)
print("12.水相平均折算速度              \t u'oa      \t",SGA.u_o_l_ave)
print("13.出口汽相折算速度              \t u''o2     \t",SGA.u_o_g)
print("14.汽相平均折算速度              \t u''oa     \t",SGA.u_o_g_ave)
print("15.水相运动粘度                 \t vl        \t",SGA.matr.nu_l)
print("16.汽相运动粘度                 \t vg        \t",SGA.matr.nu_g)
print("17.水相雷诺数                   \t Relo      \t",SGA.Re_lo)
print("18.汽相雷诺数                   \t Rego      \t",SGA.Re_go)
print("19.判别流态                     \t          \t",SGA.flow_state)
print("20.管束直段高                   \t Hs        \t",SGA.pip.l)
print("21.水相摩擦系数                 \t lamblo    \t",SGA.lamb_lo)
print("22.汽相摩擦系数                 \t lambgo    \t",SGA.lamb_go)
print("23.按折算速度计算的水相摩擦阻力    \t ΔPflo     \t",SGA.P_f_lo)
print("24.按折算速度计算的汽相摩擦阻力    \t ΔPfgo     \t",SGA.P_f_go)
print("25.参量X                       \t           \t",SGA.X)
print("26.Phi_l**2                   \t           \t",SGA.Phi_l)
print("27.Phi_g**2                   \t           \t",SGA.Phi_g)
print("28.水相摩擦阻力                 \t ΔPfl      \t",SGA.P_f_l)
print("29.汽相摩擦阻力                 \t ΔPfg      \t",SGA.P_f_g)
print("30.摩擦阻力                    \t ΔPf       \t",SGA.P_f_up)

print("2、 局部阻力")
print("1.支撑板数目                   \t N        \t",SGA.matr.N_support)
print("2.上升流道单元面积              \t Au      \t",SGA.A_u)
print("3.支撑板单元开孔面积            \t au       \t",SGA.a_u)
print("4.面积比                      \t          \t",SGA.auA)
print("5.局部阻力系数                 \t epsl     \t",SGA.epsilon_support)
print("6.按折算速度计算的水相局部阻力    \t ΔPllo    \t",SGA.P_l_lo_support)
print("7.按折算速度计算的汽相局部阻力    \t ΔPlgo    \t",SGA.P_l_go_support)
print("8.参量X                       \t           \t",SGA.X_support)
print("9.二回路工作压力               \t Ps        \t",SGA.matr.P_loop_2_s)
print("10.临界压力                   \t Pc        \t",SGA.matr.P_c)
print("11.参数ZR                    \t           \t",SGA.Z_R)
print("12.参数K                     \t           \t",SGA.K)
print("13.Phi_l                    \t           \t",SGA.Phi_l_support)
print("14.Phi_g                    \t           \t",SGA.Phi_g_support)
print("15.水相局部阻力               \t ΔPll      \t",SGA.P_l_l_support)
print("16.汽相局部阻力               \t ΔPlg      \t",SGA.P_l_g_support)
print("17.局部阻力                  \t ΔPl      \t",SGA.P_l_support)

print("3、 弯管区阻力")
print("1.管束弯头最大节圆直径        \t db        \t",SGA.d_b)
print("2.弯管区重心至圆心距离        \t ys        \t",SGA.y_s)
print("3.节距                     \t t         \t",SGA.matr.t)
print("4.计算冲刷排数              \t N'        \t",SGA.N_rush)
print("5.系数                     \t x1=x2     \t",SGA.x1x2)
print("6.系数                     \t n         \t",SGA.n_rush)
print("7.水相雷诺数                \t Relo      \t",SGA.Re_lo_rush)
print("8.汽相雷诺数                \t Rego      \t",SGA.Re_go_rush)
print("9.水相摩擦阻力系数           \t lamb_lo   \t",SGA.lamb_lo_rush)
print("10.汽相摩擦阻力系数          \t lamb_go   \t",SGA.lamb_go_rush)
print("11.全水相阻力               \t ΔPblo     \t",SGA.P_b_lo)
print("12.全汽相阻力               \t ΔPbgo     \t",SGA.P_b_go)
print("13.参量X                   \t           \t",SGA.X_rush)
print("14.Phi_l                  \t           \t",SGA.Phi_lo_rush)
print("15.Phi_g                  \t           \t",SGA.Phi_go_rush)
print("16.水相阻力                \t ΔPbl      \t",SGA.P_b_g)
print("17.汽相阻力                \t ΔPbg      \t",SGA.P_b_l)
print("18.弯管区阻力              \t ΔPb       \t",SGA.P_b)

print("4、加速阻力")
print("1.管束出口质量含汽率        \t x2        \t",SGA.x2)
print("2.管束出口体积含汽率        \t beta2     \t",SGA.beta2)
print("3.系数                    \t C         \t",SGA.C_a)
print("4.管束出口截面含汽率        \t phi2      \t",SGA.phi_2_a)
print("5.质量流速                 \t G        \t",SGA.G_a)
print("6.加速阻力                 \t ΔPa      \t",SGA.P_a)

print("5、流量分配阻力")
print("1.单元面积               \t Au'       \t",SGA.matr.A_u_distribution)
print("2.单元开孔面积            \t au'       \t",SGA.matr.a_u_distribution)
print("3.系数                   \t          \t",SGA.audAu)
print("4.阻力系数               \t epsh      \t",SGA.epsilon_h)
print("5.孔板局部阻力            \t Ph        \t",SGA.P_h)

print("6、上升空间阻力")
print("1.上升空间阻力            \t ΔPr       \t",SGA.P_r)

print("三、汽水分离器阻力")
print("1.汽水分离器阻力            \t ΔPs       \t",SGA.P_s)

print("四、循环总阻力")
print("1.循环总阻力            \t ΔP总       \t",SGA.P_loop2_tot)


print("III、运动压头计算")
print("一、预热段高度计算")
print("1.循环倍率              \t CR        \t",SGA.CR)
print("2.二回路给水焓           \t if        \t",SGA.i_f)
print("3.二回路饱和水焓         \t is        \t",SGA.i_s)
print("4.液面高度              \t Ho        \t",SGA.H_down)
print("5.下降空间水密度         \t rhod      \t",SGA.rho_f_2)
print("6.下降空间下端压力       \t Plow      \t",SGA.p_low)
print("7.plow压力下的饱和水焓   \t isl       \t",SGA.H_low)
print("8.Δi/ΔP               \t           \t",SGA.diddp)
print("9.热负荷               \t q         \t",SGA.q)
print("10.循环水量             \t G        \t",SGA.G_loop_water)
print("11.预热段高度           \t Hp       \t",SGA.H_p)

print("二、运动压头计算")
print("1.蒸发段高度                \t Hr1        \t",SGA.H_r1)
print("2.管束上方区段高度           \t Hr2        \t",SGA.H_r2)
print("3.蒸发段平均质量含汽率        \t x1a        \t",SGA.x_1_a)
print("4.蒸发段平均体积含汽率        \t beta1a     \t",SGA.beta_1_a)
print("5.蒸发段平均截面含汽率        \t phi1a      \t",SGA.Phi_1_a)
print("6.管束上方区段平均截面含汽率   \t phi2a      \t",SGA.Phi_2_a)
print("7.蒸发段运动压头             \t Pm1        \t",SGA.P_m1)
print("8.管束上方区段压头           \t Pm2        \t",SGA.P_m2)
print("9.运动压头                  \t Pm         \t",SGA.P_m)

print("附录三、蒸汽发生器强度计算")
print("一、传热管")
print("1.设计压力            \t P设1      \t",SGA.P_pip)
print("2.许用应力            \t [σ1]       \t",SGA.matr.sigma1)
print("3.管子外径            \t do        \t",SGA.matr.d_o)
print("4.直管计算壁厚         \t S''       \t",SGA.S_pip_thi)
print("5.负公差修正系数        \t phi      \t",SGA.phi_gongcha)
print("6.弯曲减薄系数         \t phiR      \t",SGA.phi_R)
print("7.计算壁厚             \t S'       \t",SGA.S_cacu)
print("8.设计壁厚             \t S        \t",SGA.S_cacu)

print("二、下筒体")
print("1.设计压力            \t P设2      \t",SGA.P_down_sp)
print("2.许用应力            \t [σ2]      \t",SGA.matr.sigma2)
print("3.筒体内径            \t Di下      \t",SGA.D_i_down)
print("4.计算壁厚            \t S'        \t",SGA.S_down_sp_c)
print("5.设计壁厚            \t S         \t",SGA.S_down_sp)
print("6.筒体外径            \t Do下      \t",SGA.D_o_down)
print("7.与管板连接壁厚       \t Si        \t",SGA.S_I_down)

print("三、上筒体")
print("1.设计压力            \t P设2      \t",SGA.P_down_sp)
print("2.许用应力            \t [σ3]      \t",SGA.matr.sigma3)
print("3.筒体内径            \t Di上      \t",SGA.D_i_up)
print("4.计算壁厚            \t S'        \t",SGA.S_up_sp_c)
print("5.设计壁厚            \t S         \t",SGA.S_up_sp)

print("四、球形下封头")
print("1.设计压力            \t P设1      \t",SGA.P_down_sp)
print("2.许用应力            \t [σ4]      \t",SGA.matr.sigma4)
print("3.球型封头外径         \t D0        \t",SGA.D_o_sp)
print("4.计算壁厚            \t S'        \t",SGA.S_downsphead_c)
print("5.设计壁厚            \t S         \t",SGA.S_downsphead)

print("五、管板")
print("1.设计压力            \t P设1      \t",SGA.P_pip)
print("2.许用应力            \t [σ1]      \t",SGA.matr.sigma5)
print("3.承压部分直径         \t do        \t",SGA.D_i_down)
print("4.筒体根部壁厚与直径比  \t           \t",SGA.SdD)
print("5.系数                \t F        \t",SGA.F_TEMA)
print("6.计算壁厚             \t S'       \t",SGA.S_plate_c)
print("7.设计壁厚             \t S        \t",SGA.S_plate)
print("8.堆焊层厚度           \t S'        \t",SGA.S_duihan)
